"""Add embedding_cache table using pgvector

Revision ID: 7a9829621a7c
Revises: 005_add_kit_bookmarks
Create Date: 2026-02-22 17:12:15.648519+00:00
"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7a9829621a7c'
down_revision: Union[str, None] = '005_add_kit_bookmarks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('embedding_cache',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('text_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding_cache')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
