"""Add LlmProviderConfig

Revision ID: ac8ba97f2c5d
Revises: db81246b347e
Create Date: 2026-03-14 07:27:42.369799+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac8ba97f2c5d'
down_revision: Union[str, None] = 'db81246b347e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_model', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_name', name='uq_user_llm_config')
    )
    op.drop_index(op.f('idx_execution_runs_user'), table_name='execution_runs')
    op.drop_index(op.f('idx_execution_runs_version'), table_name='execution_runs')
    op.drop_index(op.f('idx_reasoning_kits_owner'), table_name='reasoning_kits')
    op.drop_index(op.f('idx_reasoning_kits_public'), table_name='reasoning_kits')
    op.drop_index(op.f('idx_resources_text_search'), table_name='resources', postgresql_using='gin')
    op.alter_column('tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_resources_text_search'), 'resources', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(extracted_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_reasoning_kits_public'), 'reasoning_kits', ['is_public', 'name'], unique=False)
    op.create_index(op.f('idx_reasoning_kits_owner'), 'reasoning_kits', ['owner_id'], unique=False)
    op.create_index(op.f('idx_execution_runs_version'), 'execution_runs', ['version_id', 'started_at'], unique=False)
    op.create_index(op.f('idx_execution_runs_user'), 'execution_runs', ['user_id', 'started_at'], unique=False)
    op.drop_table('llm_provider_configs')
    # ### end Alembic commands ###
