"""add is_active to mcp_server_configs

Revision ID: 665d4571ea5e
Revises: 61f17a5f67c5
Create Date: 2026-03-01 19:58:29.593364+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665d4571ea5e'
down_revision: Union[str, None] = '61f17a5f67c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server_configs', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server_configs', 'is_active')
    # ### end Alembic commands ###
